backend:
  name: github
  repo: rguthrie04/meredith-guthrie-website # Your repo path
  branch: main # Branch to update

# Required media settings
media_folder: "src/img/uploads" # Where to store uploaded images relative to root
public_folder: "/img/uploads" # Public path to access uploaded images

collections:
  # Collection for regular pages (About, Services, Contact)
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    description: "Edit the main website pages (About, Services, Contact, Insights List)."
    # Removed folder: "src/pages" - use files list exclusively
    files:
      - label: "Homepage"
        name: "index"
        file: "src/pages/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "base.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "About Page"
        name: "about"
        file: "src/pages/about.md"
        fields: # Added fields for this file
          - {label: "Layout", name: "layout", widget: "hidden", default: "base.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/about/"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Services Page"
        name: "services"
        file: "src/pages/services.md"
        fields: # Added fields for this file
          - {label: "Layout", name: "layout", widget: "hidden", default: "base.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/services/"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Contact Page"
        name: "contact"
        file: "src/pages/contact.md"
        fields: # Added fields for this file
          - {label: "Layout", name: "layout", widget: "hidden", default: "base.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/contact/"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Insights Listing Page" # Added Insights listing page
        name: "insights_list"
        file: "src/pages/insights.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "base.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/insights/"}
          - {label: "Intro Text", name: "body", widget: "markdown"} # Note: This edits the text *above* the post list.

  # Collection for Insights (Blog Posts)
  - name: "insights"
    label: "Insights"
    label_singular: "Insight"
    folder: "src/posts" # Folder for insight markdown files
    create: true # Allow creating new insights
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename format: YYYY-MM-DD-title.md
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"} 